name: 
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    branches-ignore:
      - ci/demo-db-migrations
      - platform-*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 18.13.0
  NODE_ENV: staging
  OCASSIO_ENV_PATH: env/public
  OCASSIO_MIGRATE_ENV_PATH: ./env/migrate
  PR_NUMBER: ${{ github.event.number }}

  # Used for naming the feature DB
  GIT_BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  check-formatting:
    name: Check Code Formatting
    runs-on: [self-hosted, ARM64, staging]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node 18 install
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Prettier
        run: npx prettier --check .
  create-db:
    name: Create Feature Database and Migrate against occasio Staging DB
    runs-on: [self-hosted, ARM64, staging]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Yarn
        run: npm install --global yarn && yarn --version
      - run: yarn install
      - name: Install "just"
        uses: extractions/setup-just@v1

      - run: just drop-db
      - run: just create-db
      - run: just cmd=apply migrate
      # use below not above if you just want to migrate the existing db in the RC  - just migrate calls 'watch once'
      # - run: just set-target-test-db-env
      # - run: just migrate

  build-image:
    uses: occasio-technology-solutions/infra/.github/workflows/build-image.yaml@development
    with:
      docker-arch: linux/arm64
    secrets: inherit

  build-migration-image:
    uses: occasio-technology-solutions/infra/.github/workflows/build-image.yaml@development
    with:
      docker-arch: linux/arm64
      build-target: "migration"
    secrets: inherit
